import Head from "next/head";
import React from "react";
import Navbar from "../navbar";

interface Props {
  children?: JSX.Element;
}
const Layout: React.FC<Props> = ({ children }) => {
  return (
    <div className="flex h-screen w-screen select-none text-slate-900">
      <Head>
        <title>Trava</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-1 pt-14 pb-2">{children}</div>
      <Navbar />
    </div>
  );
};

export default Layout;
