import Head from "next/head";
import { SyntheticEvent, useState } from "react";
import { fetchData } from "../services/request";

export default function Home() {
  return (
    <div className="text-slate-900">
      <Head>
        <title>Travel App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen select-none flex-col items-center justify-center px-6"></div>
    </div>
  );
}
